/**
 * Constants related to Deal Actions.
 */
public class DealActionConstants {

    /**
     * "Accepted" status of Deal action.
     */
    public static String STATUS_ACCEPTED = 'Accepted';

    /**
     * "Rejected" status of Deal action.
     */
    public static String STATUS_REJECTED = 'Rejected';

    /**
     * empty status of Deal action.
     */
    public static String STATUS_EMPTY = '';
}